language: ruby
rvm:
- 2.1.2
env:
- DB=sqlite
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- RAILS_ENV=test bundle exec rake sunspot:solr:start
- sleep 3
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- mkdir -p tmp/cache
- mysql -e 'create database stoffi_test'
- psql -c 'create database stoffi_test' -U postgres
notifications:
  slack:
    secure: bSr6+hfaI5F6EYqPTyLtfwnC+KLMAR98EeOqoV12RVMgmBC3bUWMxslBmpqeGy2ooG347u2c2HQYM+frsx2GgvNk6mhN9QW4tfvZFlGa0UYcEB739vUCqa3lX5tsLe3CDhIud6+DFJqgCdvR93RuDbzghyM60kX5Yuk4kJDCgjBYdDW++xB1QP2oV/NDSsUfo3URW9lHYaUkaf0yK4Rs2fjIz/sdp0pxtJJ4cdOk+wAhmUJpWbZEwfVdoHBPoVXCP3vR41FHjn5s2miUIgkKUke6tfd9GLxtiZ89Jy9aly62bS0m047wwlAbwKfCC5s7KDo1lvNaUqr/LXz10bpkklweVO/ORicIhR3CP+X0TPtNLocoBYhANYSQ1JDRvhTfAILKBnyJtlmKypmKiZwus1RZVLUjFzDU1pq/irqj/pPvOkcMC2zGyLpG0onMa5nWwM57sZ54erakpUtTvnU/CnlwtLXoJOM2tBh+Z7yeyYkG5HDtGdzPAzyP5EkP0rotTRS7s/yhAYjCMeWfytHpEb+udgRMC5Bwvuv1ZjxygIomxfDhD7aMxMJAKGb712tiXTiLfZ8uu/yHxQGfregQUmmcT2WTHWB7c24eNzn9u2WnesTz/OBG5WJdsqtOJH7a3WbwKwIVPtecpnh+2rqtrWYYIK0qiRNxgqPwwI00BzM=
