se:
  pages:
    singular: 'sida'
    
    pages:
      
      error_400:
        header:          'Fel i fråga'
        text:            "Servern kan inte förstå vad det är du efterfrågar."
      
      error_403:
        header:          'Förbjudet'
        text:            "Woops! Du får inte göra det där."
      
      error_404:
        header:          'Ingen sån %{resource} finns'
        text:            'Den %{resource} som den här addressen pekar på verkar inte finnas.'
      
      error_422:
        header:          'Obearbetbar enhet'
        text:            "Det är något mysko med datan du precis skickade."
      
      error_500:
        header:          'Ett serverfel uppstod'
        text:            'Något knas uppstod. Men ta det lugnt, det var vårt fel och inte ditt. Vi fixar det så fort vi kan.'
      
      error_502:
        header:          'Dålig gateway'
        text:            "Servern har problem med en av sina tjänster. Vi fixar det så snabbt vi kan."
      
      error_503:
        header:          'Överbelastning'
        text:            "Servern är upptagen för tillfället. Vänligen försök igen om en liten stund."
      
      index:
        link:            'Hem'
        description:     'Stoffi Musikspelare är en vacker, integrerad, kompakt &amp; gratis musikspelare som spelar musik från YouTube, SoundCloud, radio och din hårddisk.'
  
      donations:
        link:            'Donera'
        title:           'Visa din kärlek'
        description_html: '<p>Stoffi är ett hobbyprojekt som betalas av mig, Christoffer, helt ur egen ficka.</p><p>Gillar du projektet får du gärna visa din uppskattning genom att donera en slant.</p>'
  
      news:
        link:            'Nyheter'
        title:           'Senaste nyheterna'
        description:     'Läs om våra senaste släpp, lär dig vilka nya features som kommit och spana in våra screenshots.'
  
      about:
        link:            'Om'
        title:           'Om'
        description:     'Lär dig mer om Stoffi och gänget bakom.'
  
      get:
        link:            'Ladda ner'
        title:           'Skaffa den'
        description:     'Ladda ner Stoffi Musikspelare helt gratis och utan några extra bundles, addons eller annat skräp.'
  
      tour:
        link:            'Tur'
        title:           'Ta en rundtur'
        description:     'Lär dig mer om Stoffi genom att spana in vår rundtur som visar några av de coolaste delarna av denna underbara musikspelare.'
  
      download:
        link:            'Ladda ner'
        title:           'Ladda ner'
        description:     'Tack för att du laddar hem Stoffi Musikspelare. Se till att följa oss på Twitter, Facebook och läs vår blogg för mer information.'
    
      old:
        title:           'Gammal webbläsare'
        description:     'Du använder en gammal och övergiven webbläsare. Detta är väldigt farligt och du borde undvika att vara ute på Internet.'
  
      contact:
        link:            'Kontakt'
        title:           'Kontakta oss'
        description:     'Du kan kontakta oss om problem du har, information du saknar eller vad som helst egentligen.'
        
      contribute:
        link:            'Hjälp till'
        title:           'Hjälp till med Stoffi'
        description:     'asd.'
  
      legal:
        link:            'Regler'
        title:           'Regler'
        description:     'Stoffis kod är öppen, gratis att ladda hem, ändra och använda. Vi har starkt fokus på ditt privatliv och säljer aldrig vidare några uppgifter till andra parter.'
  
      money:
        link:            'Pengar'
        title:           'Pengar, pengar, pengar'
        description:     "Med Stoffi kan du skicka pengar säkert till dina favoritartister. Vi uppskattar att du ger oss förtroende över dina pengar och vill se till att du kan påverka och bestämma hur just dina pengar ska fördelas."
  
      remote:
        link:            'Fjärrkontroll'
        title:           'Fjärrkontroll'
        description:     'Styr din Stoffi-spelare genom ett lättanvänt webbgränssnitt.'
        