us:
  artists:
    plural: "artists"
    singular: "artist"
    
    songs: 'Popular songs'
    albums: 'Albums'
    events: 'Upcoming events'
    
    meta:
      info: 'Information'
      name: 'Name'
      stats: 'Statistics'
      listens: 'Plays'
      songs: 'Songs'
    