us:
  contact:
    issue:
      title: "Found a bug? Have an idea?"
      text_html: "Go to our %{link} and submit an issue."
      link: "project"
      
    email:
      title: "Email us"
      name: "Your name"
      email: "Your email"
      subject: "Subject"
      message: "Message"
      captcha: "Are you human?"
      send: "Send"
      sent: "Your message has been sent. You should hear from us soon."
    
    phone:
      title: "Call us"
    
    visit:
      title: "Visit us"
      sweden: "SWEDEN"
      map:
        link: "View larger map"
        marker: 'This is where we hang around'
    
    errors:
      subject: "Subject must be at least four characters."
      name: "Your name is certainly more than one character."
      message: "Message must be at least twenty characters."
      email: "You forgot your e-mail."
      captcha: "I'm sure you are a human. Try again."
