se:
  links:
    share:
      title: 'Dela'
      description: 'Publisera saker du delar.'
      
    listen:
      title: 'Spelningar'
      description: 'Publisera låtar du lyssnar på.'
      
    create_playlist:
      title: 'Spellistor'
      description: 'Publisera spellistor du skapar.'
      
    show_button:
      title: 'Sociala knappar'
      description: 'Visa %{label}knapp på dina spellistor och profil.'
      labels:
        twitter: 'följa'
        google_oauth2: '+'
        default: 'social '