se:
  songs:
    plural: "låtar"
    singular: "låt"
    description: '%{song}, en låt av %{artists}'
    similar: 'Liknande låtar'
    top:
      title: "Populära låtar"
    meta:
      header: 'Metadata'
      title: 'Titel'
      artists: 'Artister'
      genres: 'Genrar'
      length: 'Längd'
      listens: 'Spelningar'
      listeners: 'Lyssnare'
    albums: 'Med i dessa album'