us:
  songs:
    plural: "songs"
    singular: "song"
    description: '%{song}, a song by %{artists}'
    similar: 'Similar songs'
    top:
      title: "Popular songs"
    meta:
      header: 'Meta data'
      title: 'Title'
      artists: 'Artists'
      genres: 'Genres'
      length: 'Length'
      listens: 'Plays'
      listeners: 'Listeners'
    albums: 'Appears in these albums'