json.listens charts_listens_for_user_url(format: :json)
json.songs charts_songs_for_user_url(format: :json)
json.playlists charts_playlists_for_user_url(format: :json)
json.artists charts_artists_for_user_url(format: :json)
json.albums charts_albums_for_user_url(format: :json)
json.genres charts_genres_for_user_url(format: :json)
