test:
  secret_key_base: secretkey
  devise: secretkey
  recaptcha:
    public: publickey
    private: secretkey
  oa_cred:
    echonest:
      id: somerandomid
    facebook:
      id: somerandomid
      key: secretkey
      url: https://graph.facebook.com
    foursquare:
      id: somerandomid
      key: secretkey
      url: https://foursquare.com
    google_oauth2:
      id: somerandomid
      key: secretkey
      url: https://www.googleapis.com
    lastfm:
      id: somerandomid
      key: secretkey
      url: http://ws.audioscrobbler.com
    linkedin:
      id: somerandomid
      key: secretkey
      url: http://api.linkedin.com
    myspace:
      id: somerandomid
      key: secretkey
      url: http://api.myspace.com
    rdio:
      id: somerandomid
      key: secretkey
    soundcloud:
      id: somerandomid
      key: secretkey
      url: https://api.soundcloud.com
    twitter:
      id: somerandomid
      key: secretkey
      url: https://api.twitter.com
    windowslive:
      id: somerandomid
      key: secretkey
      url: https://apis.live.net
    yandex:
      id: somerandomid
      key: secretkey
    yahoo:
      id: somerandomid
      key: secretkey
      url: http://social.yahooapis.com
    youtube:
      key: secretkey
      url: https://www.googleapis.com/youtube/v3
    vimeo:
      id: somerandomid
      key: secretkey
      url: http://vimeo.com
    vkontakte:
      id: 123
      key: secretkey
      url: http://api.vk.com
    weibo:
      id: 123
      key: secretkey

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_KEY"] %>
  recaptcha:
    public: <%= ENV["RECAPTCHA_PUBLIC"] %>
    private: <%= ENV["RECAPTCHA_PRIVATE"] %>
  split:
    username: <%= ENV["SPLIT_USERNAME"] %>
    password: <%= ENV["SPLIT_PASSWORD"] %>
  oa_cred:
    echonest:
      id: <%= ENV["ECHONEST_ID"] %>
    facebook:
      id: <%= ENV["FACEBOOK_ID"] %>
      key: <%= ENV["FACEBOOK_KEY"] %>
      url: https://graph.facebook.com
    foursquare:
      id: <%= ENV["FOURSQUARE_ID"] %>
      key: <%= ENV["FOURSQUARE_KEY"] %>
      url: https://foursquare.com
    google_oauth2:
      id: <%= ENV["GOOGLE_ID"] %>
      key: <%= ENV["GOOGLE_KEY"] %>
      url: https://www.googleapis.com
    lastfm:
      id: <%= ENV["LASTFM_ID"] %>
      key: <%= ENV["LASTFM_KEY"] %>
      url: http://ws.audioscrobbler.com
    linkedin:
      id: <%= ENV["LINKEDIN_ID"] %>
      key: <%= ENV["LINKEDIN_KEY"] %>
      url: http://api.linkedin.com
    myspace:
      id: <%= ENV["MYSPACE_ID"] %>
      key: <%= ENV["MYSPACE_KEY"] %>
      url: http://api.myspace.com
    rdio:
      id: <%= ENV["RDIO_ID"] %>
      key: <%= ENV["RDIO_KEY"] %>
    soundcloud:
      id: <%= ENV["SOUNDCLOUD_ID"] %>
      key: <%= ENV["SOUNDCLOUD_KEY"] %>
      url: https://api.soundcloud.com
    twitter:
      id: <%= ENV["TWITTER_ID"] %>
      key: <%= ENV["TWITTER_KEY"] %>
      url: https://api.twitter.com
    windowslive:
      id: <%= ENV["WINDOWS_ID"] %>
      key: <%= ENV["WINDOWS_KEY"] %>
      url: https://apis.live.net
    yandex:
      id: <%= ENV["YANDEX_ID"] %>
      key: <%= ENV["YANDEX_KEY"] %>
    yahoo:
      id: <%= ENV["YAHOO_ID"] %>
      key: <%= ENV["YAHOO_KEY"] %>
      url: http://social.yahooapis.com
    youtube:
      key: <%= ENV["YOUTUBE_KEY"] %>
      url: https://www.googleapis.com/youtube/v3
    vimeo:
      id: <%= ENV["VIMEO_ID"] %>
      key: <%= ENV["VIMEO_KEY"] %>
      url: http://vimeo.com
    vkontakte:
      id: <%= ENV["VKONTAKTE_ID"] %>
      key: <%= ENV["VKONTAKTE_KEY"] %>
      url: http://api.vk.com
    weibo:
      id: <%= ENV["WEIBO_ID"] %>
      key: <%= ENV["WEIBO_KEY"] %>
      
development: *production